config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'

  post '/lead' => 'pages#post_lead'

  get '/lead(.:id)' => 'pages#download_lead'

  get '/residential' => 'pages#residential'

  get '/corporate' => 'pages#corporate'

  get '/quote' => 'pages#quote'

  post '/quote' => 'pages#post_quote', as: 'post_quote'

  post '/starwars' => 'pages#star_wars'

  get "pages/index"

  get '/intervention' => 'pages#intervention'
  get '/intervention/get_data' => 'pages#intervention_get_data'
  post 'intervention' => 'pages#post_intervention'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if Employee.where(user_id: user.id).exists?
      can :manage, :all
    elsif Customer.where(user_id: user.id).exists?
      can :access, :rails_admin
      can :read, :dashboard
      can :index, User,["id = ?", user.id] do |user|
        user.present?
      end
      can :index, Customer, user_id: user.id
      can :index, Elevator, ["column_id = ?", user.customer.building.battery.column.id] do |elevator|
        elevator.present?
      end
      can :index, Building, ["customer_id = ?", user.customer.id] do |building|
        building.present?
      end
      can :index, Battery,["building_id = ?", user.customer.building.id] do |battery|
      battery.present?
      end
      can :index, BuildingDetail, ["building_id = ?", user.customer.building.id] do |detail|
       detail.present?
      end
      can :index, Column,["battery_id = ?", user.customer.building.battery.id] do |column|
        column.present?
      end
    else
      return
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :customer
    has_one :building
end

app/models/battery.rb
class Battery < ApplicationRecord
  belongs_to :building
  belongs_to :employee
  
  has_one :column
  has_many :intervention, foreign_key: :BatteryID
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :customer
  belongs_to :address

  has_one :building_detail
  has_one :battery
  has_many :intervention, foreign_key: :BuildingID
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery

    has_one :elevator
    has_many :intervention, foreign_key: :ColumnID
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
    belongs_to :address

    has_one :building
    has_many :intervention, foreign_key: :CustomerID
end

app/models/dim_customer.rb
class DimCustomer < WarehouseRecord
    include RailsAdminCharts

    def self.graph_data since=30.days.ago 
    data = []


    DimCustomer.all.each do |key|
    data.push({
        name: key.ContactFullname,
        pointInterval: point_interval = 1.day * 1000,
        pointStart: start_point = since.to_i * 1000,
        data: [key.NbElevator.to_i]
    })
    end

    data
    end

    def self.chart_type
        "column"
    end
end

app/models/elevator.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'rubygems'
require 'twilio-ruby'
require 'slack-notifier'
require 'dotenv'


class Elevator < ApplicationRecord
  belongs_to :column
  has_many :intervention, foreign_key: :ElevatorID
  before_save :send_txt
  before_update :slack_notifier

  def userid
    return self.Column.battery.building.customer.user.id
  end

  def send_txt
    if self.Status_changed?
      
      if self.Status == "Intervention"
		
		phone_to = self.column.battery.building.BuildingTechPhone
    
    sms = "Mr/Mrs #{self.column.battery.building.BuildingTechFullName} The Elevator ID: #{self.id} located at #{self.column.battery.building.address.NumberAndStreet}, #{self.column.battery.building.address.City} with Serial Number #{self.serialNumber} changed status to #{self.Status}"
		account_sid = ENV['TWILIO_ACCOUNT_SID']
		auth_token = ENV['TWILIO_AUTH_TOKEN']
		@client = Twilio::REST::Client.new(account_sid, auth_token)

		message = @client.messages.create(
									body: sms,
									from: '+15812058687',
									to: phone_to
								)
    

      end
    end
    
  end
  
  def slack_notifier
    if self.Status_changed?
      require 'date'
      current_time = DateTime.now.strftime("%d-%m-%Y %H:%M")
      notifier = Slack::Notifier.new ENV["SLACK_API_WEBHOOK_URL"]  do
        defaults channel: "#elevators_operations"
      end
      notifier.ping "The Elevator #{self.id} with Serial Number #{self.serialNumber} changed status from #{self.Status_was} to #{self.Status} at #{current_time}."
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_one :battery

  def fullname
    "#{self.firstname}  #{self.lastname}"
   end

   has_many :intervention, foreign_key: :AuthorID
   has_many :intervention, foreign_key: :EmployeeID
end

app/models/fact_contact.rb
class FactContact < WarehouseRecord
    include RailsAdminCharts

    def self.graph_data since=30.days.ago 
    data = []


    FactContact.all.group_by {|u| u.CreationDate.beginning_of_month }.each do |key , value|
    data.push({
        name: key.strftime("%Y-%m"),
        pointInterval: point_interval = 1.day * 1000,
        pointStart: start_point = since.to_i * 1000,
        data: [value.size]
    })
    end

    data
    end

    def self.chart_type
        "column"
    end
end

app/models/fact_elevator.rb
class FactElevator < WarehouseRecord
end

app/models/fact_intervention.rb
class FactIntervention < WarehouseRecord
end

app/models/fact_quote.rb
class FactQuote < WarehouseRecord
    include RailsAdminCharts

    def self.graph_data since=30.days.ago 
    data = []


    FactQuote.all.group_by {|u| u.CreationDate.beginning_of_month }.each do |key , value|
        data.push({
            name: key.strftime("%Y-%m"),
            pointInterval: point_interval = 1.day * 1000,
            pointStart: start_point = since.to_i * 1000,
            data: [value.size]
        })
        end
    

    data
    end

    def self.chart_type
        "column"
    end
end

app/models/intervention.rb
class Intervention < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :building, optional: true
  belongs_to :battery, optional: true
  belongs_to :column, optional: true
  belongs_to :elevator, optional: true
  belongs_to :employee, optional: true


end

app/models/lead.rb
class Lead < ApplicationRecord
    #before_save :set_default

   #protected

   #def set_default
     #self.download = "To download the attached file, click on :  Show in app"
   #end
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee
  has_one :customer
end

app/models/warehouse_record.rb
class WarehouseRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"warehouse_#{Rails.env}"
end

app/views/layouts/_footer.html.erb
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3 class="letter-spacing-1">WHY US?</h3>
                <p>Ask our customers and you will know why you will want our elevators.</p>
                <p>Alternatively, call us and we'll answer your questions.</p>
                <h2>(581) 701-0303</h2>
            </div>
        </div>
    </div>
    <div class="copyright">
        <div class="container">
            <ul class="float-right m-0 list-inline mobile-block">
                <li><a>Terms &amp; Conditions</a></li>
                <li>&bull;</li>
                <li><a>Privacy</a></li>
            </ul>&copy; All Rights Reserved, Rocket Elevators
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-toggleable-md sticky header-md clearfix" id="header">
    <header id="topNav">
        <div class="container">
            <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse"><i class="fa fa-bars"></i></button><a class="logo flat-left scrollTo" href="/"><img src="/assets/rocket_elevators/logo.png"></a>
            <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                <nav class="nav-main">
                    <ul class="nav nav-pills nav-main" id="topMain">
                        <li><%= link_to "Home", root_path %></li>
                        <li class="dropdown"><a class="dropdown-toggle">Services</a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Residential", residential_path %></li>
                                <li><%= link_to "Corporate", corporate_path %></li>
                                <li><%= link_to "Get a quote", quote_path %></li>
                            </ul>
                        </li>
                        <li><%= link_to "Portfolio", root_path(anchor: "work") %></li>
                        <li><%= link_to "News", root_path(anchor: "news") %></li>
                        <li><%= link_to "Clients", root_path(anchor: "clients") %></li>
                        <li><%= link_to "Contact", root_path(anchor: "contact") %></li>
                        <li class="dropdown"><a class="dropdown-toggle">Account</a>
                            <ul class="dropdown-menu">
                                <% if current_user.present? %>
                                <% if can? :access, :rails_admin %>
                                <li><%= link_to "Backoffice", rails_admin_path %></li>
                                <% end %>
                                <% if is_employee? %>
                                <li><%= link_to "Intervention", intervention_path %></li>
                                <%end %>
                                <li><%= link_to('Edit account', edit_user_registration_path) %></li>
                                <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
                                <%else%>
                                <li><%= link_to "Sign in", new_user_session_path %></li>
                                <li><%= link_to "Sign up", new_user_registration_path %></li>
                                <% end %>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />


    <% if content_for? :for_head %>
    <%= yield :for_head %>
    <%else%>
    <title>Rocket Elevators</title>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="description" content="Elevate safety, speed and style" />
    <meta name="Author" content="Frédéric Choquette [https://github.com/frederic2ec]" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <!-- Mobile settings-->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!-- Web fonts-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />
    <!-- Core CSS-->
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Revolution slider-->
    <link href="/assets/plugins/slider.revolution/css/extralayers.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/slider.revolution/css/settings.css" rel="stylesheet" type="text/css" />
    <!-- Theme CSS -->
    <%= stylesheet_link_tag "essentials.css", media: "all", "data-turbolinks-track" => "reload" %>
    <%= stylesheet_link_tag "layout.css", media: "all", "data-turbolinks-track" => "reload" %>
    <!-- Page level scripts-->
    <%= stylesheet_link_tag "header-1.css", media: "all", "data-turbolinks-track" => "reload" %>
    <%= stylesheet_link_tag "red.css", media: "all", "data-turbolinks-track" => "reload" %>
</head>

<body class="smoothscroll enable-animation">
    <div id="wrapper">
        <%= render 'layouts/header'%>

        <%= yield %>

        <%= render 'layouts/footer'%>
    </div>

    <!-- Scroll to top--><a href="#" id="toTop"></a>
    <!-- Javascript files-->
    <script>
        var plugin_path = '/assets/plugins/';
    </script>
    <script src="/assets/plugins/jquery/jquery-3.5.1.min.js"></script>

    <%= javascript_include_tag "scripts.js" %>
    <%= javascript_include_tag "newsletter.js" %>
    <script src="/assets/plugins/slider.revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="/assets/plugins/slider.revolution/js/jquery.themepunch.revolution.min.js"></script>
    <%= javascript_include_tag "revolution_slider.js" %>

    <% if content_for? :for_foot %>
    <%= yield :for_foot %>
    <% end %>

</body>

</html>

app/views/pages/corporate.html.erb
<% content_for :for_head do %>
<title>Rocket Elevators - Corporate Buildings</title>
<% end %>

<div class="slider fullwidthbanner-container roundedcorners">
    <div class="fullwidthbanner" data-height="600" data-shadow="0" data-navigationStyle="preview2">
        <ul class="hide">
            <li data-transition="parallaxtotop" data-slotamount="7" data-masterspeed="300" data-saveperformance="off" data-title="Residential buildings"><img src="/assets/rocket_elevators/AdobeStock_179073967.jpeg" alt="cover image" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat" />
                <div class="overlay dark-4"></div>
                <div class="tp-caption font-roboto skewfromleft tp-resizeme" data-x="50" data-y="100" data-speed="500" data-start="1500" data-easing="Cubic.easeOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="500" style="z-index: 2; color:#fff; font-size:65px; line-height:85px; font-weight:bold; letter-spacing:0;">Corporate buildings</div>
                <div class="tp-caption skewfromrightshort tp-resizeme" data-x="50" data-y="300" data-speed="500" data-start="1000" data-easing="easeInCirc" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-endspeed="500" style="z-index: 3; font-size:20px; color:#fff; font-weight:300;;">We offer corporate service for your building !</div>
                <div class="tp-caption sfb tp-resizeme" data-x="50" data-y="410" data-speed="500" data-start="1500" data-easing="Power3.easeIn" data-splitin="none" data-splitout="none" data-elementdelay="1" data-endelementdelay="0.1" data-endspeed="500" style="z-index: 4; max-width: auto;"><a class="btn btn-default btn-lg" href="/quote#">GET A QUOTE &nbsp;<i class="fa fa-angle-right"></i></a></div>
            </li>
        </ul>
    </div>
</div>
<!-- Seperator-->
<hr class="m-0" />
<!-- Services-->
<section id="overview">
    <div class="container text-center">
        <div class="row text-left">
            <div class="col-sm-8"><img class="img-fluid" src="/assets/rocket_elevators/AdobeStock_78149317.jpeg" /></div>
            <div class="col-sm-4">
                <h3 class="fw-300">Corporate<span> Elevator</span></h3>
                <p>The greatest elevators built out of military grade material and engineered by the best of the bests.</p>
                <p>These elevator are designed to fit your corporate building aesthetically and they also have the best elevator music.</p>
                <hr />
                <ul class="list-unstyled list-icons">
                    <li><i class="fa fa-check"> </i>Up to the best standard</li>
                    <li><i class="fa fa-check"> </i>Fast</li>
                    <li><i class="fa fa-check"> </i>Sensational</li>
                    <li><i class="fa fa-check"> </i>Visually pleasing</li>
                    <li><i class="fa fa-check"> </i>Secures</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- Banner-->
<section class="container">
    <div class="text-center">
        <h2 class="m-0">Did we convinced you ?</h2>
        <div class="mt-30"><a class="btn btn-primary ntn-lg" href="/quote#">GET A QUOTE &raquo;</a></div>
    </div>
</section>

app/views/pages/intervention.html.erb
<% content_for :for_head do %>
<title>Rocket Elevators - Intervention</title>
<% end %>
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <%= form_with(url: "/intervention", :html => {:class => 'cartContent clearfix'} ) do %>
                <fieldset>
                    <div class="row">
                        <div class="col-md-4"><label>Customer</label><%= select_tag('customer', options_from_collection_for_select(Customer.all, "id", "FullNameOfContact"), prompt: "--- Select ---", required: "required", class: "form-control pointer", id: 'customer-select') %></div>
                        <div class="col-md-4"><label>Building</label><%= select_tag('building', options_for_select([['--- Select ---', '']]), required: "required", class: "form-control pointer", id: 'building-select') %></div>
                        <div class="col-md-4"><label>Battery</label><%= select_tag('battery', options_for_select([['--- Select ---', '']]), required: "required", class: "form-control pointer", id: 'battery-select') %></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><label>Column</label><%= select_tag('column', options_for_select([['--- Select ---', '']]), required: "required", class: "form-control pointer", id: 'column-select') %></div>
                        <div class="col-md-4"><label>Elevator</label><%= select_tag('elevator', options_for_select([['--- Select ---', '']]), required: "required", class: "form-control pointer", id: 'elevator-select') %></div>
                        <div class="col-md-4"><label>Employee</label><%= select_tag('employee', options_from_collection_for_select(Employee.all, "id", "fullname"), prompt: "--- Select ---", required: "required", class: "form-control pointer", id: 'employee-select') %></div>
                    </div>
                    <div>
                        <div class=col-md-12><label>Description</label><%= text_area_tag('report', nil, id: 'description', required: "required", class: "form-control", rows: 8, maxlength: 1000) %></div>
                    </div>
                    <hr />
                </fieldset>
                <%= recaptcha_tags %>
                <%= submit_tag("Submit", class: "btn btn-primary")  %>
                <% end %>
            </div>
        </div>
    </div>
</section>

<% content_for :for_foot do %>
<%= javascript_include_tag "intervention.js", "data-turbolinks-track" => "reload" %>
<% end %>

app/views/pages/quote.html.erb
<% content_for :for_head do %>
<title>Rocket Elevators - Get a quote</title>
<%= stylesheet_link_tag "layout-shop.css", media: "all", "data-turbolinks-track" => "reload" %>
<% end %>

<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<%end %>

<!-- Header-->
<section class="page-header page-header-xs">
    <div class="container">
        <h1>GET A QUOTE</h1>
        <ol class="breadcrumb">
            <li><a href="/#">Home</a></li>
            <li><a href="/#services">Services</a></li>
            <li><a class="active" href="/quote#">Get a quote</a></li>
        </ol>
    </div>
</section>
<!-- Quote-->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-sm-8">
                <%= form_with(url: "/quote", :html => {:class => 'cartContent clearfix'} ) do %>
                <fieldset>
                    <div class="row">
                        <div class="col-md-4"><label for="contact:name">Full Name</label><%= text_field_tag('fullname', nil, id: 'building-name', required: "required", class: "form-control") %></div>
                        <div class="col-md-4"><label for="contact:email">E-mail Address</label><%= email_field_tag('email', nil, id: 'building-email',required: "required", class: "form-control") %></div>
                        <div class="col-md-4"><label for="contact:phone">Phone</label><%= telephone_field_tag('phone', nil, id: 'building-phone', required: "required", class: "form-control") %></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4"><label for="contact:subject">Business Name</label><%= text_field_tag('businessname', nil, id: 'building-business', required: "required", class: "form-control") %></div>
                        <div class="col-md-4"><label for="contact:subject">Project Name</label><%= text_field_tag('projectname',nil, id: 'building-project', required: "required", class: "form-control") %></div>
                        <div class="col-md-4"><label for="contact_department">Building Type</label><%= select_tag('buildingtype', options_for_select([['--- Select ---', ''], ['Residential', 'Residential'],['Commercial', 'Commercial'], ['Corporate', 'Corporate'], ['Hybrid', 'Hybrid']]), required: "required", class: "form-control pointer", id: 'building-select') %></div>
                    </div>
                    <hr />
                    <!-- Residential-->
                    <div class="row" id="residential-form">
                        <div class="col-md-4"><label for="contact:subject">Number of apartment</label><%= number_field_tag('nbapartment',nil, id: 'residential-apartment', required: "required", class: "form-control") %></div>
                        <div class="col-md-4"><label for="contact:subject">Number of floor</label><%= number_field_tag('nbfloor',nil, id: 'residential-floor', required: "required", class: "form-control") %></div>
                        <div class="col-md-4"><label for="contact:subject">Number of basement</label><%= number_field_tag('nbbasement',nil, id: 'residential-basement', required: "required", class: "form-control") %></div>
                    </div>
                    <!-- Commercial-->
                    <div id="commercial-form">
                        <div class="row">
                            <div class="col-md-4"><label for="contact:subject">Number of business</label><%= number_field_tag('nbbusiness',nil, id: 'commercial-business', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of floor</label><%= number_field_tag('nbfloor',nil, id: 'commercial-floor', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of basement</label><%= number_field_tag('nbbasement',nil, id: 'commercial-basement', required: "required", class: "form-control") %></div>
                        </div>
                        <div class="row">
                            <div class="col-md-6"><label for="contact:subject">Number of parking</label><%= number_field_tag('nbparking',nil, id: 'commercial-parking', required: "required", class: "form-control") %></div>
                            <div class="col-md-6"><label for="contact:subject">Number of shaft</label><%= number_field_tag('nbshaft',nil, id: 'commercial-shaft', required: "required", class: "form-control") %></div>
                        </div>
                    </div>
                    <!-- Corporate-->
                    <div id="corporate-form">
                        <div class="row">
                            <div class="col-md-4"><label for="contact:subject">Number of companies</label><%= number_field_tag('nbcompanies',nil, id: 'corporate-companies', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of floor</label><%= number_field_tag('nbfloor',nil, id: 'corporate-floor', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of basement</label><%= number_field_tag('nbbasement',nil, id: 'corporate-basement', required: "required", class: "form-control") %></div>
                        </div>
                        <div class="row">
                            <div class="col-md-6"><label for="contact:subject">Number of parking</label><%= number_field_tag('nbparking',nil, id: 'corporate-parking', required: "required", class: "form-control") %></div>
                            <div class="col-md-6"><label for="contact:subject">Number of occupant/floor</label><%= number_field_tag('nboccupant',nil, id: 'corporate-occupant', required: "required", class: "form-control") %></div>
                        </div>
                    </div>
                    <!-- Hybrid-->
                    <div id="hybrid-form">
                        <div class="row">
                            <div class="col-md-4"><label for="contact:subject">Number of business</label><%= number_field_tag('nbbusiness',nil, id: 'hybrid-business', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of floor</label><%= number_field_tag('nbfloor',nil, id: 'hybrid-floor', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of basement</label><%= number_field_tag('nbbasement',nil, id: 'hybrid-basement', required: "required", class: "form-control") %></div>
                        </div>
                        <div class="row">
                            <div class="col-md-4"><label for="contact:subject">Number of parking</label><%= number_field_tag('nbparking',nil, id: 'hybrid-parking', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact:subject">Number of occupant/floor</label><%= number_field_tag('nboccupant',nil, id: 'hybrid-occupant', required: "required", class: "form-control") %></div>
                            <div class="col-md-4"><label for="contact_department">Active hours/day</label><%= select_tag('activehours', options_for_select([['--- Select ---', ''], [0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20],[21],[22],[23],[24]]), required: "required", class: "form-control pointer", id: 'hybrid-active') %></div>
                        </div>
                    </div>
                    <!-- Quality-->
                    <div class="row">
                        <div class="col-md-12">
                            <label class="radio"><%= radio_button_tag('quality', 'standard', true, required: 'required') %><i></i>Standard</label>
                            <label class="radio"><%= radio_button_tag('quality', 'premium', false, required: 'required') %><i></i>Premium</label>
                            <label class="radio"><%= radio_button_tag('quality', 'excelium', false, required: 'required') %><i></i>Excelium</label>
                        </div>
                    </div>
                </fieldset>
                <input type="hidden" id="nbelevator" name="nbelevator" value="">
                <input type="hidden" id="elevatorprice" name="elevatorprice" value="">
                <input type="hidden" id="subtotal" name="subtotal" value="">
                <input type="hidden" id="installfee" name="installfee" value="">
                <input type="hidden" id="total" name="total" value="">
                <%= recaptcha_tags %>
                <%= submit_tag("Submit", class: "btn btn-primary")  %>
                <% end %>
            </div>
            <div class="col-lg-3 col-sm-4">
                <div class="toggle-transparent toggle-bordered-full clearfix">
                    <div class="toggle active">
                        <div class="toggle-content"><span class="clearfix"><span class="float-right" id="elevator-number">--</span><span class="float-left">Number of elevator:</span></span><span class="clearfix"><span class="float-right" id="elevator-price">--</span><span class="float-left">Price/elevator:</span></span>
                            <span class="clearfix"><span class="float-right" id="elevator-subtotal">--</span><span class="float-left">Subtotal:</span></span><span class="clearfix"><span class="float-right" id="elevator-fee">--</span><span class="float-left">Install fee:</span></span>
                            <hr /><span class="clearfix"><span class="float-right fs-20" id="elevator-total">--</span><strong class="float-left">TOTAL:</strong></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<% content_for :for_foot do %>
<%= javascript_include_tag "quote.js", "data-turbolinks-track" => "reload" %>
<% end %>